version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: pylint
    versions:
    - 2.6.1
    - 2.7.0
    - 2.7.3
    - 2.8.0
  - dependency-name: astroid
    versions:
    - 2.5.4
    - 2.5.5
  - dependency-name: importlib-metadata
    versions:
    - 3.6.0
    - 3.8.0
    - 3.8.1
    - 3.9.0
    - 3.9.1
    - 4.0.0
  - dependency-name: amqp
    versions:
    - 5.0.5
    - 5.0.6
  - dependency-name: django-extensions
    versions:
    - 3.1.1.post1
  - dependency-name: faker
    versions:
    - 6.2.0
    - 6.5.1
    - 6.5.2
    - 6.6.1
    - 7.0.0
  - dependency-name: djangorestframework
    versions:
    - 3.12.3
  - dependency-name: s3transfer
    versions:
    - 0.3.5
  - dependency-name: defusedxml
    versions:
    - 0.7.0
  - dependency-name: path
    versions:
    - 15.1.1
  - dependency-name: cryptography
    versions:
    - 3.3.2
    - "3.4"
    - 3.4.2
    - 3.4.3
    - 3.4.5
  - dependency-name: sentry-sdk
    versions:
    - 0.20.0
    - 0.20.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.16
  - dependency-name: webpack
    versions:
    - 5.20.0
    - 5.34.0
  - dependency-name: cypress
    versions:
    - 6.7.0
    - 6.7.1
    - 7.0.0
    - 7.0.1
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: react-bootstrap
    versions:
    - 1.5.1
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.16
