language: python
dist: bionic
addons:
  firefox: "81.0"
  apt:
    packages:
      # for Cypress
      - libgconf-2-4
env:
  - TEST_SUITE=eslint
  - TEST_SUITE=jstest
  - TEST_SUITE=jenkins
  - TEST_SUITE=cypress
python:
  - "3.6"
services:
  - postgresql
before_script:
  - psql -c 'create database test_mediathread;' -U postgres
cache:
  npm: true
  pip: true
  directories:
    # for Cypress
    - ~/.cache
script:
  - make $TEST_SUITE
